#!name=AdGuard DNS
#!desc=Подключение DNS для блокировки рекламы
#!arguments=LocalDNS:quic://dns.adguard-dns.com

#quic://dns.adguard-dns.com
#https://dns.adguard-dns.com/dns-query
#tls://dns.adguard-dns.com

[General]
dns-server = LocalDNS

[Host]
[Host]
twitch.tv =  server:1.1.1.1
*.twitch.tv = server:1.1.1.1
ttvnw.net = server:1.1.1.1
*.ttvnw.net = server:1.1.1.1
twitchcdn.net = server:1.1.1.1
*.twitchcdn.net = server:1.1.1.1
jtvnw.net = server:1.1.1.1
*.jtvnw.net = server:1.1.1.1