#!name=AdBlock DNS
#!desc=Подключение DNS для блокировки рекламы
#!arguments=LocalDNS:quic://dns.adguard-dns.com

#quic://dns.adguard-dns.com
#https://dns.adguard-dns.com/dns-query
#tls://dns.adguard-dns.com

[General]
dns-server = LocalDNS

[Host]
twitch.tv = server:syslib
*.twitch.tv = server:syslib
ttvnw.net = server:syslib
*.ttvnw.net = server:syslib
twitchcdn.net = server:syslib
*.twitchcdn.net = server:syslib
jtvnw.net = server:syslib
*.jtvnw.net = server:syslib