#!name=Ad Guard DNS
#!desc=Подключение DNS для блокировки рекламы
#quic://dns.adguard-dns.com
#https://dns.adguard-dns.com/dns-query
#tls://dns.adguard-dns.com

[General]
dns-server = quic://dns.adguard-dns.com

[Host]
twitch.tv = server:https://cloudflare-dns.com/dns-query
*.twitch.tv = server:https://cloudflare-dns.com/dns-query
ttvnw.net = server:https://cloudflare-dns.com/dns-query
*.ttvnw.net = server:https://cloudflare-dns.com/dns-query
twitchcdn.net = server:https://cloudflare-dns.com/dns-query
*.twitchcdn.net = server:https://cloudflare-dns.com/dns-query
jtvnw.net = server:https://cloudflare-dns.com/dns-query
*.jtvnw.net = server:https://cloudflare-dns.com/dns-query
