#!name=Busuu Premium
#!desc=Разблокировка платного функционала Busuu
#https://github.com/iSteal-it/script

[Script]
bussu = type = http-response, script-path=https://raw.githubusercontent.com/llanguor/Shadowrocket/main/Modules/Scripts/Busuu_Premium.json,pattern=^https:\/\/api\.busuu\.com\/users\/me,max-size=131072,requires-body=true,timeout=10,enable=true

[MITM]
hostname = %APPEND% api.busuu.com
