#!name=Spotify Premium
#!desc=Часичное сняие ограничений бесплатной версии

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://github.com/itcast-l/shadowrocket-module/raw/main/js/Spotify.js,script-update-interval=0
