#!name=Spotify Premium
#!desc=Частичное снятие ограничений бесплатной версии
#https://github.com/StricklandF/shadowrocket-module/tree/main

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/llanguor/Shadowrocket/refs/heads/main/Modules/Spotify_Premium.js,script-update-interval=0
