#!name=UNO Ads Block
#!desc=UNO Ads Block
#!url=https://raw.githubusercontent.com/llanguor/Shadowrocket/refs/heads/main/Modules/UNO%20Ads%20Block.sgmodule

[RULE]
DOMAIN-KEYWORD,inmobi,REJECT
DOMAIN-KEYWORD,rayjump,REJECT
DOMAIN-KEYWORD,appsflyersdk,REJECT
DOMAIN-KEYWORD,unityads,REJECT
DOMAIN-KEYWORD,applvn,REJECT
DOMAIN-KEYWORD,liftoff-creative,REJECT
DOMAIN-KEYWORD,liftoff,REJECT
DOMAIN-KEYWORD,vungle,REJECT
DOMAIN-KEYWORD,applovin,REJECT
