#!name=YouTube Premium Source
#!desc=Картинка в картинке и блокировка рекламы для YouTube
# Origin Author: @DivineEngine, @app2smile, @Maasea, @VirgilClyne# Other hints: @Choler, @bai1zi# Merged and released by @ddgksf2013 in form of qx# Translated and refined for shadowrocket by @deezertidal

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Url Rewrite]
#Для работы всего функционала
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad _ reject-200

#Ускорение шортсов - их пропуск в обход модуля
#^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?|el=shortspage|ctier=SH|initplayback.*&opf=1)).+&oad _ reject-200
#^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?|el=shortspage|ctier=SH|initplayback.*&opf=1|initplayback.*&owc=1)).+&oad _ reject-200
#^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?|el=shortspage|ctier=SH|initplayback.*&opf=1|initplayback.*&owc=1|initcwndbps=(?:[0-9]{1,6}|1[0-6]\d{5}|17[0-3]\d{4}))).+&oad _ reject-200
#^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?|el=shortspage|ctier=SH|initplayback.*&opf=1|initplayback.*&owc=1|initcwndbps=(?:[0-9]{1,6}|1[0-6]\d{5}))).+&oad _ reject-200

#Починено next. Некоторые шортсы идут в обработку
#^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?|el=shortspage|ctier=SH|initcwndbps=(?:[0-9]{1,6}|[12]\d{6}).*&opf=1|initplayback.*&owc=1|initcwndbps=(?:[0-9]{1,6}|1[0-6]\d{5}))).+&oad _ reject-200


#Блокировка рекламы Universal
#^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads _ reject-200
#^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext _ reject-200
#С этой строкой долгая загрузка в шортсах при первом запуске. Раскомментить если будет реклама
#^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) _ reject-200

#Блокировка рекламы General video
#(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302

[Script]
#Фоновое воспроизведение и картинка в картинке
#youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine={{{scriptExecutionEngine}}},script-path=https://raw.githubusercontent.com/llanguor/Shadowrocket/refs/heads/main/Modules/Scripts/YouTube_Premium.js,argument="{"lyricLang":"{{{lyricLang}}}","captionLang":"{{{captionLang}}}","blockUpload":{{{blockUpload}}},"blockImmersive":{{{blockImmersive}}},"debug":{{{debug}}}}"
#Убраны упоминания Shorts
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine={{{scriptExecutionEngine}}},script-path=https://raw.githubusercontent.com/llanguor/Shadowrocket/refs/heads/main/Modules/Scripts/YouTube_Premium.js,argument="{"lyricLang":"{{{lyricLang}}}","captionLang":"{{{captionLang}}}","blockUpload":{{{blockUpload}}},"blockImmersive":{{{blockImmersive}}},"debug":{{{debug}}}}"

[MITM]
#Указывает какие домены расшифровывать 
hostname = %APPEND% -redirector*.googlevideo.com,*.googlevideo.com,www.youtube.com,s.youtube.com,youtubei.googleapis.com
