#!name=YouTube Premium
#!desc=Картинка в картинке и блокировка рекламы для YouTube
# Origin Author: @DivineEngine, @app2smile, @Maasea, @VirgilClyne# Other hints: @Choler, @bai1zi# Merged and released by @ddgksf2013 in form of qx# Translated and refined for shadowrocket by @deezertidal

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[Url Rewrite]
#Блокировка рекламы??? или что то еще? С этим правилом долго грузятся шортсы
#^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad _ reject-200
#Было заменено на это. Если будет в будущем реклама - править
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?|initplayback.*&pxtags=Cg4KAnR4Egg1MTM5OTk3Mg)).+&oad _ reject-200

#Блокировка рекламы Universal
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads _ reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) _ reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext _ reject-200

#Блокировка рекламы General video
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302

[Script]
#Фоновое воспроизведение и картинка в картинке
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine={{{scriptExecutionEngine}}},script-path=https://raw.githubusercontent.com/llanguor/Shadowrocket/refs/heads/main/Modules/youtube.response.preview.js,argument="{"lyricLang":"{{{lyricLang}}}","captionLang":"{{{captionLang}}}","blockUpload":{{{blockUpload}}},"blockImmersive":{{{blockImmersive}}},"debug":{{{debug}}}}"

[MITM]
#Указывает какие домены расшифровывать 
hostname = %APPEND% -redirector*.googlevideo.com,*.googlevideo.com,www.youtube.com,s.youtube.com,youtubei.googleapis.com
